### ISSUE TITLE
Creating Husarion project fails when at enable_module

### ISSUE THREAD

**Issue by sausthapit** [husarion/hFramework#52]
I am following your [tutorial ](https://husarion.com/tutorials/other-tutorials/hframework-library-development/) to create a new Husarion project on Ubuntu. I have installed Visual Studio Code and  hFramework is successfully compiled.
This is the command I am running and its output
cmake .. -DBOARD_TYPE=core2 -DPORT=stm32 -DHFRAMEWORK_PATH=/home/saurav/hFramework -GNinja
CMake Deprecation Warning at /home/saurav/hFramework/hFrameworkPort.cmake:3 (cmake_policy):
  The OLD behavior for policy CMP0011 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  /home/saurav/hFramework/hFramework.cmake:18 (include)
  CMakeLists.txt:4 (include)

-- Using hFramework from workspace
This is module path:
CMake Error at /home/saurav/hFramework/hFramework.cmake:40 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  CMakeLists.txt:8 (enable_module)

-- Using module from workspace: 
-- Configuring incomplete, errors occurred!
See also "/home/saurav/leo_firmware/CMakeFiles/CMakeOutput.log".

Looking inside the enable_module macro, 
COMMAND "${HFRAMEWORK_PATH}/../hcommon/hdev-findmodule" ${name}

it is looking for hdev-findmodule file which I believe is not installed.

Could you please help.
Thanks

**Comment by lukaszmitka** [comment]
Hello sausthapit,

I need some clarification, first you wrote that "hFramework is successfully compiled" then you are unable to build hFramework, did you change anything during the process?

On the other hand, when you install VSCode with Husarion extension, you are getting hFramework built and ready to use.
You can proceed to [creating Husarion project](https://husarion.com/tutorials/other-tutorials/offline-development-tools/#offline-development-tools-for-linux) step.

Regards,
Łukasz

**Comment by sausthapit** [comment]
Hi Lukasz,
Thanks for replying, I installed the extension and also compiled from the source on github. While I was compiling my firmware, I was using the wrong hFrameworkPath. Once I used the path to the Husarion extension, there was no more error.
Regards,
Saurav
